### ISSUE TITLE
주제선정

### ISSUE THREAD

**Issue by KimGyeongLock** [KimGyeongLock/Lab13#2]
CRUD Mini project

**Comment by KimGyeongLock** [comment]
도서관 도서 관리 시스템

**Comment by KimGyeongLock** [comment]
1. 도서관 현황
2. 도서관 대출 가능 유무

**Comment by suminyoo** [comment]
책을 빌려가거나 사가면 delete, 새로 들여오면 create
아니면 대출 목록으로 할까요? 둘다 상관없을것 같은데 어떤게 나으세요?

**Comment by KimGyeongLock** [comment]
저는 약간 도서관에 있는 컴퓨터 도서 대출 목록을 생각했었어서 
struct에 다가 대출가능 이라는 variable을 넣고 OX로 구분해도 될 거 같다고 생각을 해봤어요

**Comment by suminyoo** [comment]
아 좋네요 대출목록으로 하는게 좋을거 같아요. 
기본적인 CRUD기능이랑 save load 랑 검색기능이랑 넣을 수 있는데. 검색은 어떻게 검색 할 수 있게하는게 좋을까요? 대출된 것 안된 것 검색이나 이름으로 검색할 수 있게 할까요?

**Comment by KimGyeongLock** [comment]
네 좋을 거 같네요!! 주제는 이렇게 하고 역할분담은 다른 page 열게요!!
