### ISSUE TITLE
역할 분담

### ISSUE THREAD

**Issue by KimGyeongLock** [KimGyeongLock/Lab13#3]
1. CRUD 기능 
2. 데이터 파일 저장/읽어오기
3. 검색 등 메뉴(종료메뉴 제외) 등
 10개 이상 함수 정의(구조체도 정의)

**Comment by suminyoo** [comment]
역할 분담이 어떻게 할 수 있는거죠? 일단 두명으로선 함수를 나눠서 작성 하는건가요?
해왔던대로 CRUD 4개랑, 메뉴보기,  list, select, save, load, 검색 하면 10가지 되서 분담할 수 있을거 같은데, 다른 어떤 기능 추가하거나 검색기능 더 추가해볼까요?

**Comment by KimGyeongLock** [comment]
책을 가나다 순으로 정렬하는 거나..

**Comment by suminyoo** [comment]
정렬 괜찮네요. 검색기능은 아까 말한 대출여부랑 이름 검색만 넣을까요? 
대출여부로 분류한다면 그 책의 값들은 삭제된 값은 아니고 보존되는데 대출여부만 바뀌는것일텐데
책이 아예 없어지는 것이랑 대출하는것이랑 하나로 할까요 아니면 두개가 나을까요

**Comment by KimGyeongLock** [comment]
책을 아예 없애는 것은 딱히 필요없을 거 같고 저는 그냥 대출여부를 기준으로 delete할 때 삭제용으로 쓰려고 했어요!

**Comment by suminyoo** [comment]
아 delete하면 대출여부변수가 변경되는 것이군요. 맞나요? 그럼 main 함수랑 다른 함수들 다해서 12개 가지고 나눌 수 있을 것 같네요

**Comment by KimGyeongLock** [comment]
네네!
